# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.


External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [3]:
import pandas as pd


In [4]:
auto_df= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
auto_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323


In [5]:
auto_df.tail()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [6]:
auto_df.shape   #to determine the number of rows and columns in the dataset

(4008, 11)

In [7]:
auto_df.dtypes['Customer']  #to determine the data type of the 'Customer' column; should have been string data type but it is an object data type


dtype('O')

In [34]:
auto_df.dtypes[['Customer', 'ST','Education', 'GENDER','Customer Lifetime Value','Income','Monthly Premium Auto', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class', 'Total Claim Amount']]  #to determine the data type of the columns; should have been string data type but it is an object data type

Customer                      object
ST                            object
Education                     object
GENDER                        object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

Customer, ST, Education, GENDER, Customer Lifetime Value,  Policy Type and Vehicle Class should have been string data type but are an object data type.
Number of Open Complaints is classified as an object data type but should have been an integer data type.
Income is a float data type but could have been an integer data type.
Monthly Premium Auto is a float data type, its fine to be a float data type.
Total Claim Amount is a float data type and is fine.

In [18]:
auto_df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [19]:
auto_df['Customer'].unique()    # to display the unique values in the 'Customer' column

array(['RB50392', 'QZ44356', 'AI49188', ..., 'CW49887', 'MY31220', nan],
      dtype=object)

CATEGORICAL DATA

In [38]:
auto_df[['ST', 'GENDER', 'Education', 'Policy Type', 'Vehicle Class']].nunique()  # to display the unique values in the categorical columns

ST               8
GENDER           5
Education        6
Policy Type      3
Vehicle Class    6
dtype: int64

In [20]:
auto_df['ST'].unique()  # ST has 9 including 'nan' unique values, can be classified as categorical  data.

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [21]:
auto_df['GENDER'].unique() # GENDER has 6 unique values, which can be fixed to 2 as male and female and is a categorical (Nominal) data type.

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [22]:
auto_df['Education'].unique() # Education has 7 unique values including 'nan' and is a categorical (Nominal) data type.

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [24]:
auto_df['Policy Type'].unique()    # Policy Type has 4 unique values including 'nan' and is a categorical (Nominal) data type.

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

In [25]:
auto_df['Vehicle Class'].unique()  # Vehicle Class has 7 unique values including 'nan' and is a categorical data type.

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

NUMERICAL DATA

In [26]:
auto_df['Income'].min() 

0.0

In [27]:
auto_df['Income'].max() 

99960.0

In [ ]:
auto_df['Number of Open Complaints'].unique() # Number of Open Complaints has 7 unique values including 'nan'and is a categorical data but should have been a numerical data type.

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

Range for Income is between 0 to 99960.0

In [28]:
auto_df['Monthly Premium Auto'].min() 

61.0

In [29]:
auto_df['Monthly Premium Auto'].max() 

35354.0

Range for Monthly Premium Auto is between 61.0 to 35354.0

In [30]:
auto_df['Total Claim Amount'].min() 

0.38210700000000003

In [31]:
auto_df['Total Claim Amount'].max() 

2893.239678

Range for Total Claim Amount is between 0.38210 to 2893.2396

In [91]:
Statistics_of_data=auto_df[['Income', 'Monthly Premium Auto', 'Total Claim Amount']].describe().T # to display the summary statistics of the numerical columns
print("Summary statistics for numerical data are:", '\n', Statistics_of_data)

Summary statistics for numerical data are: 
                        count          mean           std        min  \
Income                1071.0  39295.701214  30469.427060   0.000000   
Monthly Premium Auto  1071.0    193.234360   1601.190369  61.000000   
Total Claim Amount    1071.0    404.986909    293.027260   0.382107   

                               25%           50%      75%           max  
Income                14072.000000  36234.000000  64631.0  99960.000000  
Monthly Premium Auto     68.000000     83.000000    109.5  35354.000000  
Total Claim Amount      202.157702    354.729129    532.8   2893.239678  


In [87]:
median_nummercial_data= auto_df[['Income', 'Monthly Premium Auto', 'Total Claim Amount']].median()
print("Median values for numerical data are:",'\n', median_nummercial_data)

Median values for numerical data are: 
 Income                  36234.000000
Monthly Premium Auto       83.000000
Total Claim Amount        354.729129
dtype: float64


In [44]:
auto_df[['Income', 'Monthly Premium Auto', 'Total Claim Amount']].mode()

,Income,Monthly Premium Auto,Total Claim Amount
0,0.0,65.0,321.6


## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [49]:
auto_df['ST'].value_counts()

Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: ST, dtype: int64

In [84]:
location_frequencies= auto_df['ST'].value_counts()
top_5_less_common_states=location_frequencies.sort_values().head(5)
print("Five most less common customer locations are:", '\n',top_5_less_common_states)

Five most less common customer locations are: 
 AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: ST, dtype: int64


### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*


In [52]:
auto_df['Policy Type'].count()

1071

In [60]:
policy_sold = auto_df['Policy Type'].value_counts()
print(policy_sold)

Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: Policy Type, dtype: int64


In [80]:
policy_sold=auto_df['Policy Type'].value_counts().idxmax()  # using idmax() to get the most sold policy type.
print("Highest number of policy sold are frm policy type:",policy_sold)

Highest number of policy sold are frm policy type: Personal Auto


In [ ]:
# policy_least_sold=auto_df['Policy Type'].value_counts().idxmin()
# policy_least_sold

'Special Auto'

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [73]:
personal_auto_policy= auto_df.loc[auto_df['Policy Type'] == 'Personal Auto']
corporate_auto_policy= auto_df.loc[auto_df['Policy Type']=='Corporate Auto']
personal_average_income = personal_auto_policy['Income'].mean()
corporate_average_income = corporate_auto_policy['Income'].mean()
print(f"Average Income for Personal Auto Policy: {personal_average_income}")
print(f"Average Income for Corporate Auto Policy: {corporate_average_income}")

Average Income for Personal Auto Policy: 38180.69871794872
Average Income for Corporate Auto Policy: 41390.31196581197


### Bonus: Exercise 4


Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data. 

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [92]:
auto_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [124]:
total_claim_amount = auto_df['Total Claim Amount']
sorted_claim_amount= total_claim_amount.sort_values(ascending=False)
print (sorted_claim_amount.head())
print(sorted_claim_amount.describe().T)
threshold= sorted_claim_amount.quantile(0.75)
max_claim= sorted_claim_amount[sorted_claim_amount > threshold]
print("Claim above 75th percentile:", '\n', max_claim)


888    2893.239678
248    2345.413441
522    2027.724442
196    1836.000000
581    1577.674417
Name: Total Claim Amount, dtype: float64
count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64
Claim above 75th percentile: 
 888     2893.239678
248     2345.413441
522     2027.724442
196     1836.000000
581     1577.674417
           ...     
590      537.600000
290      537.600000
648      537.600000
66       537.600000
1070     537.600000
Name: Total Claim Amount, Length: 264, dtype: float64
